### PR TITLE
[DE-709] Implementación de storybook

### PR DESCRIPTION
**Pull request by Cromeror**
Bajo el mismo formato que tenemos **/documentation/{{environment|PR-#}}/** agregamos la ruta **/storybook** para ver la documentación.

**_Ejemplo:_**
- https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-110/storybook/
- https://cdn.fromdoppler.com/doppler-style-guide/documentation/main/storybook/
- https://cdn.fromdoppler.com/doppler-style-guide/documentation/INT/storybook/

image

### CODE REVIEW

**Comment by andresmoschini** [comment]
image

Do you think that it is possible adding at least one example of our current components?

I think that it is useful to easily detect potential problems. Maybe you already did that and you want to merge only this in order to make the PR smaller, in that case 🚀

**Comment by andresmoschini** [comment]
Also, what do you think about making it minimalistic and removing some items, for example, the header or the content of the start page?

**Comment by Cromeror** [comment]
> Do you think that it is possible adding at least one example of our current components?
> 
> I think that it is useful to easily detect potential problems. Maybe you already did that and you want to merge only this in > > >order to make the PR smaller, in that case 🚀

Yes, you are right! this PR is just a minimal commit with basic configuration adjusted our need.

**Comment by Cromeror** [comment]
In the next commit I will push our documentation, the basic problems.

**Pull request merged**
